# Generated by Django 5.0.6 on 2024-07-08 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('agent_type', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound'), ('', '')], default='', max_length=20)),
                ('salesperson_name', models.CharField(default='', max_length=55)),
                ('salesperson_role', models.CharField(default='', max_length=255)),
                ('company_name', models.CharField(default='', max_length=255)),
                ('company_business', models.TextField(default='')),
                ('agent_response', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
