# Generated by Django 5.0.6 on 2024-07-11 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salesperson_name', models.CharField(max_length=100)),
                ('salesperson_role', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_business', models.CharField(max_length=1000)),
                ('company_values', models.CharField(max_length=1000)),
                ('conversation_purpose', models.CharField(max_length=1000)),
                ('conversation_further_information', models.CharField(max_length=2000)),
                ('QNA', models.CharField(max_length=2000)),
                ('conversation_type', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('appointment-setter', 'Appointment Setter'), ('customer-support', 'Customer Support'), ('inbound', 'Inbound'), ('Game NPC', 'Game NPC')], max_length=255)),
                ('generated_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
