# Generated by Django 5.0.6 on 2024-07-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_promptrecord_delete_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptrecord',
            name='assistance_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
