# Generated by Django 5.0.6 on 2024-07-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_promptrecord_assistance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_sid', models.CharField(max_length=50)),
                ('twilio_token', models.CharField(max_length=50)),
                ('twilio_number', models.CharField(max_length=20)),
                ('label_name', models.CharField(max_length=100)),
            ],
        ),
    ]
