# Generated by Django 5.0.6 on 2024-08-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_agentresponse_calllog_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentresponse',
            name='analysis',
            field=models.TextField(default=''),
        ),
    ]
