# Generated by Django 5.0.6 on 2024-08-28 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_remove_agentresponse_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='log_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
