# Generated by Django 5.0.6 on 2024-08-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_agentresponse_created_at_agentresponse_log_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentresponse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agentresponse',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='agentresponse',
            name='analysis',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='agentresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
