# Generated by Django 5.0.6 on 2024-08-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_remove_agentresponse_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentresponse',
            name='call_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='from_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agentresponse',
            name='to_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
