# Generated by Django 5.0.6 on 2024-09-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_agentresponse_endedreason_agentresponse_assistant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentresponse',
            name='analysis',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
