# Generated by Django 5.0.6 on 2024-09-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_alter_agentresponse_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentresponse',
            name='converstional_status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agentresponse',
            name='analysis',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
