# Generated by Django 5.0.6 on 2024-09-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_remove_agentresponse_call_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentresponse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agentresponse',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='twilioinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='twilioinfo',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='agentresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='twilioinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
