# Generated by Django 5.0.6 on 2024-09-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0020_delete_calllog_delete_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptrecord',
            name='welcome_message',
            field=models.CharField(default='', max_length=555),
        ),
    ]
