# Generated by Django 5.0.6 on 2024-10-10 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0025_alter_contact_user_alter_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Api.user'),
        ),
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Api.user'),
        ),
    ]
