# Generated by Django 5.0.6 on 2024-11-02 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0028_alter_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentresponse',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.user'),
        ),
    ]
